package com.ibm.cicsdev.restappext.record;
import com.ibm.jzos.fields.*;

// Generated by IBM Record Generator for Java V3.0.0 Build 20170904-1704 on: Mon Oct 30 16:20:23 GMT 2017

public class IdentityRecord {
	protected static CobolDatatypeFactory factory = new CobolDatatypeFactory();
	static { factory.setStringTrimDefault(false); } 

	/** <pre>
	*
	*****************************************************************
	 01  IDENTITY. </pre> */
	public static final int IDENTITY_len = 16; 

	/** <pre>
	*****************************************************************
	 01  IDENTITY. </pre> */
	protected static final StringField CICS_USERID = factory.getStringField(8);

	/** <pre>
	 01  IDENTITY. </pre> */
	protected static final StringField JAVA_PRINCIPAL = factory.getStringField(8);

	protected byte[] _byteBuffer;
	// Instance variables used to cache field values
	protected String cicsUserid;
	protected String javaPrincipal;


	public IdentityRecord (byte[] buffer) {
		this._byteBuffer = buffer;
	}

	public IdentityRecord () {
		this._byteBuffer = new byte[IDENTITY_len];
	}

	public byte[] getByteBuffer() {
		return _byteBuffer;
	}


	public String getCicsUserid() {
		if (cicsUserid == null) {
			cicsUserid = CICS_USERID.getString(_byteBuffer);
		}
		return cicsUserid;
	}

	public void setCicsUserid(String cicsUserid) {
		if (CICS_USERID.equals(this.cicsUserid, cicsUserid)) {
			return;
		}
		CICS_USERID.putString(cicsUserid, _byteBuffer);
		this.cicsUserid = cicsUserid;
	}

	public String getJavaPrincipal() {
		if (javaPrincipal == null) {
			javaPrincipal = JAVA_PRINCIPAL.getString(_byteBuffer);
		}
		return javaPrincipal;
	}

	public void setJavaPrincipal(String javaPrincipal) {
		if (JAVA_PRINCIPAL.equals(this.javaPrincipal, javaPrincipal)) {
			return;
		}
		JAVA_PRINCIPAL.putString(javaPrincipal, _byteBuffer);
		this.javaPrincipal = javaPrincipal;
	}

}
